# Write a program to take your name as input and print it.
# Write a program to take your age as input and print:
# (My age is <age>)
# Write a program to take two inputs: first name and last name, and print them together.
# Write a program that asks the user:(Enter your favorite language:
# )and prints the entered value.

# ANSWER 1
name = input("enter your name : ");
print("welcome : ", name);

# Answer 2
age = input("enter your age : ");
print("your age is : ", age);

# Answer 3

firstName = input("Enter your first name : ");
lastName = input("Enter your last name : ");
print("your full name is : ", firstName, lastName);

# Answer 4
lang = input("Enter your fav. language ");
print("your fav. lang is : ", lang);
